#!/bin/sh

/usr/bin/invoke_app "$@" -C @tool/bin/AngiogenCC3D.sh -t AngiogenCC3D \
                         -u compucell3d-4.1.1 \
                         -w captive \
                         -r none
