#!/bin/sh

/usr/bin/invoke_app "$@" -C @tool/bin/AngiogenCC3D.sh -t angiogencc3d \
                         -u compucell3d-4.2.2 \
                         -w captive \
                         -r none
